apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  labels:
    app: chat
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: eftech93/chat-frontend:latest
        env:
        - name: REACT_APP_WS_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: chat-configs
              key: backend_domain
        - name: PORT
          value: "4000"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: chat-test.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-frontend
                port: 
                  number: 4000
